spring:
  application:
    name: library-event-producer
  profiles:
    active: local # prod dev qa

---
spring:
  config:
    activate:
      on-profile: local

  kafka:
    topic: "library-events"
    producer:
      bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer  # Integer due to LibraryEventId in the entity class
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    admin:
      properties:
        bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
---
#spring:
#  config:
#    activate:
#      on-profile: dev
#  kafka:
#    producer:
#      bootstrap-servers: dev:9092
#      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer  # Integer due to LibraryEventId in the entity class
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#---
#spring:
#  config:
#    activate:
#      on-profile: prod
#  kafka:
#    producer:
#      bootstrap-servers: prod:9092
#      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer  # Integer due to LibraryEventId in the entity class
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer